language: go
go:
- 1.8
- 1.7
- tip
sudo: false

env:
- secure: "YCK6MdOicgWfaDClpoBNwXdG16zGz2QqN+bA2QNFDN3j4yN9Kd1EO+e0jq1pEwnDPsDEQm2x1ZRekWSXtxvp3WBQIiiUFQeoqNYf6CVvNyo7WLafovhXUfGhS3oGGuH6HjRnteUK0ZueDvvuhv2j5y4UOLi/GYwBtgZFNWgqoYk="


install: make setup

script: make check test-cover

deploy:
  provider: releases
  api_key:
    secure: D2fwuS7n54ZkjfRmLMEAnwR2lQLa5xd+4s0l65pI6UN4ljVfQwQiFdZXaZWFr8PYSTKTm0UPj6Iqqw7VOl8I6iDzcaOqN3hoh5mDaJ7kyo7GZRPodwK9MKdOp5dPw459L2Atll8kxb4iYmfnjmcl0lDCUuWvMxXx+zgiFTB7BO0=
  skip_cleanup: true
  on:
    tags: true
    go: 1.8
